# Generated by Django 4.2.16 on 2024-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_application_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
